### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by Oswualdo** [karoly-hars/DE_resnet_unet_hyb#1]
Can you share the training code of the network?

**Comment by karoly-hars** [comment]
Hey,
I do not really have the training code in a presentable format.
I was planning to refactor it and upload it to the repo, but I never found the time.
If you provide an email address I am happy to send you the old/messy version.

**Comment by Oswualdo** [comment]
I would really appreciate it, my email is oswualdoaq@gmail.com
Thank you very much in advance

**Comment by tomashlehmann** [comment]
Hi, could you also send me the training code? I would be really happy to see how that's was trained :)
tomash.lehmann@gmail.com

**Comment by Khoronus** [comment]
Hi, thank you for sharing the code.
Could you share the training code of the network?
moro@robot.t.u-tokyo.ac.jp
