### ISSUE TITLE
How to get depth?

### ISSUE THREAD

**Issue by BhAem** [karoly-hars/DE_resnet_unet_hyb#10]
Hi, thanks for your code. I have some questions. Is the data inside the 'output' `output = model(inp)` the depth in meters? By the way, could you share the training code of the network? My email is w1193916378@gmail.com. Thanks a lot.

**Comment by karoly-hars** [comment]
Hello,

The depth is in meters.

The training code won't be available. Don't have access to the data or to the rest of the codebase anymore, so I can't provide it for you. Sorry.
