### ISSUE TITLE
How can I train my custom data?

### ISSUE THREAD

**Issue by kimtaehyeong** [karoly-hars/DE_resnet_unet_hyb#2]
Hello,
I want to learn from the dataset I have.
How do i configure my dataset and how can i train it?

Thank you.

**Comment by karoly-hars** [comment]
Hi,

The training code is currently not part of the repo. Within the next couple of weeks, I will do a bit of refactoring, and I plan to include a script for training.

If you are in a hurry, provide an e-mail address and I will send you the script I used for training 2 years ago (however, that code is slightly messy, and it is tailored for the NYU depth dataset).

**Comment by kimtaehyeong** [comment]
Hello.
Thank you for your answer.
My address is 'kimtaehyeong62@gmail.com' I am very honored to have sent you, your precious code. Thank you.

**Comment by xtsoukala** [comment]
Hi @karoly-hars, thanks for this repo! I'm also interested in the training code, have you pushed it somewhere? Or could you send it to my e-mail (x.tsoukala@gmail.com)? Thanks again!
