### ISSUE TITLE
How to get depth of an object inside a certain bounding box

### ISSUE THREAD

**Issue by shahaamirbader** [karoly-hars/DE_resnet_unet_hyb#9]
The code is really good. I am getting good results. However, I would like to get a depth prediction of a certain object within an image. I have the bounding box coordinates for that object.

Is there a way to amend the code such that I could pass in the bbox coordinates as argument and get the depth in meters displayed on terminal.

Thanks

**Comment by karoly-hars** [comment]
I would just take the average of the depth values within the bounding box, or the pixel depth in the middle of the box. Feel free to fork and experiment.
